### ISSUE TITLE
Build Apache Spark job to extract text from PDF resumes

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#1]
The program will start with a repository of 3,000 resumes in PDF format. The first task will be to build an Apache Spark job to extract text from these PDF files. Apache Tika is the library that you should use. It supports PDF along with a number of other formats out of the box.

**Comment by gilberbe** [comment]
ResumeReader scala process successfully extracts text from PDF resumes.  Currently running as a standalone script, can package up with dependencies as a "fat jar" to run using "spark-submit"
