### ISSUE TITLE
Create blog post content

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#102]
Create a blog post for the Data Works website describing the 9 week program and what the team worked on. Create the content in a google doc and we'll have it uploaded to the site once complete.

Example post from last year: http://dataworks-inc.com/project-data-walks-summer-internship-2015/

**Comment by dhuang89** [comment]
Google doc : https://docs.google.com/document/d/1FLOjZ0vKrbbcGpgCg5d5_WTIwtT0zrNDVndNv78Cfzc/edit#

**Comment by acobb6** [comment]
has been written, but can still be added to if need be until it is uploaded to the website
