### ISSUE TITLE
Add feature scores to elasticsearch and app

### ISSUE THREAD

**Issue by goubew** [dataworks/internship-2016#103]
Right now the feature scores are all combined into a single score. This is good for ranking applicants, but some of the data is lost in the combination. By storing these feature scores, users of the application can see exactly which areas of a resume are good or bad.

**Comment by goubew** [comment]
Elasticsearch now holds data about the feature scores for each applicant.

The next step is to display this info within the app.

**Comment by dhuang89** [comment]
info is now displayed in the Score Breakdown hidden row. next step is just to format it

**Comment by davidmezzetti** [comment]
Still work to be done on formatting the data in the app

**Comment by gilberbe** [comment]
Changed tuples (_1, _2) to map for features

**Comment by acobb6** [comment]
the broken down data is now displayed in a graph under each applicants drop down menus
