### ISSUE TITLE
Highlight search terms

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#108]
When a user queries, the app should highlight search terms. This should be handled on the node.js/elasticsearch end. See the following article, this can be done on the _all field. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

This will wrap terms with em tags. The front end css can be styled. I suggest a yellow or blue background color like a highlight marker.

**Comment by dhuang89** [comment]
search terms are now highlighted
