### ISSUE TITLE
Client App Code Cleanup

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#111]
A couple of the files on the Angular side have grown larger than we would like. We should look at ways to better modularize the code. 

**Tasks**

1.) Ensure all functions in the controllers are set on the scope parameter. For example $scope.displayGraph = function(...

2.) Move charting functions to a new service (see searchService.js for an example). You should look consolidating the logic in applicantController and analysisController using this service.

3.) Look into ways to split applicantView into separate templates via ngInclude. Examples include the advanced search form and carousel for graphs, 

Make sure to coordinate with the team as these changes are made. Watch for merge issues.

**Comment by dhuang89** [comment]
1 and 2 have been done. 3 is nearly there, but it breaks some functionalities. Autocomplete now updates its suggestions after the search query has been executed, and the charts will sometimes randomly disappear.

**Comment by dhuang89** [comment]
autocomplete has been fixed
