### ISSUE TITLE
Refactor Logistic Regression Model Builder and Score Calculator to use settings from Elasticsearch

### ISSUE THREAD

**Issue by gilberbe** [dataworks/internship-2016#113]
Right now our machine learning algorithm is using hard-coded values to generate the logistic regression model.  We need to get these values from an Elasticsearch index instead so they may be changed from the user interface.

**Comment by goubew** [comment]
The machine learning can now be configured from the Elasticsearch index, but still there still needs to be some kind of page on the front-end to configure these values.

**Comment by goubew** [comment]
We are in the process of the refactor refactor. Once done, we should be able to configure our machine learning models with any number of any configuration of features. What is left to do is:
- [ ] Make the base feature sub classes store the FeatureSetting that is associated with them
- [ ] Change logistic feature generator to create the base feature objects out of the setting object and allow it to create the feature scores from the list of base features
- [ ] Test everything to make sure it works as expected
- [ ] Merge back into the master branch

**Comment by goubew** [comment]
The weight are looking back to normal, but there is problem associating feature names to scores. To fix we we need to move the mapping methods from the object to the class.

**Comment by gilberbe** [comment]
Adding MaxDistance to proximity feature so we can change how far we want to look for candidates

**Comment by gilberbe** [comment]
,
