### ISSUE TITLE
Autocomplete is inserting a space

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#122]
Autocomplete is inserting a leading space when selecting a term to complete. Could this be related to the advanced search change to support advanced searches when there is no search text?

**Comment by dhuang89** [comment]
Advanced searches when there is no search text does not affect the leading space for suggestions. I'll look into this further and give updates once I found the source.

**Comment by dhuang89** [comment]
Fixed the issue by adding .trim() in autocomplete.js. I guess autocomplete always added leading whitespace, but we never noticed it.
