### ISSUE TITLE
Drastically reduce proximity feature

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#123]
The proximity raw value should be close to 1.0 for within 40 miles but drastically tail down once outside of that range. Examples below:

Reston VA -> Fairfax, VA 0.95
Reston VA -> Fredericksburg VA 0.7
Reston VA -> Richmond VA 0.5
Reston VA -> Durham NC 0.3
Reston VA -> St. Louis MO 0.15
Reston VA -> San Jose CA 0

**Comment by gilberbe** [comment]
Proximity feature is pulling its max distance from Elasticsearch's settings index (to be altered from admin page on app).  To scale it down we just have to change the feature value on ES
