### ISSUE TITLE
Use HTML5Mode for Angular URLs

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#16]
The following article shows you how to have a better pattern for URLs in a single page Angular app.

https://scotch.io/tutorials/pretty-urls-in-angularjs-removing-the-hashtag

**Comment by dhuang89** [comment]
added $locationProvider and made the URLs have a better pattern

**Comment by dhuang89** [comment]
adding locationProvider broke web app on Jenkins

**Comment by dhuang89** [comment]
fixed issue by following http://www.seankenny.me/blog/2013/08/05/angularjs-in-html5-mode-with-expressjs/ and listening to David's wisdom

**Comment by davidmezzetti** [comment]
To finish this up:

1.) Change base href to:
<base href='/app/'>

2.) 

--- a/app/server/server.js
+++ b/app/server/server.js

 var express = require("express");
 var elasticsearch = require("elasticsearch");
+var root = express();
 var app = express();
  
-var server = app.listen(8082, function () {
+root.get("/", function(req, res) {
+    res.redirect("/app");
+});
+
+root.use('/app', app);
+
+var server = root.listen(8082, function () {
   var host = server.address().address
   var port = server.address().port

**Comment by dhuang89** [comment]
fixed URLs
