### ISSUE TITLE
Remove Eclipse files from etl folder

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#18]
Given that the team is now using Github Atom, the Eclipse .project, .classpath, .cache-main and .cache-tests files along with the .settings folder should be removed.

Once done, the .classpath file should be added to the .gitignore file. Then the .run file should be moved to .classpath. The scripts in the scripts directory will need to be updated to use .classpath instead of .run.

After this the .gitignore file should look like this:

.classpath
data
model
project
target

**Comment by goubew** [comment]
Removed Eclipse files from etl and app.
Updated the .gitignore files.
Updated etl scripts to use .classpath instead of .run.
