### ISSUE TITLE
Enhance Apache Spark text extraction job to load data into Elasticsearch

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#2]
The main repository for storing data will be Elasticsearch. Use the elasticsearch-hadoop plugin to load each text resume into Elasticsearch.

**Comment by gilberbe** [comment]
Successfully connected Apache Spark to the Elasticsearch database, resumes are stored using the unique file name as the doc id, and the full extracted text is stored in the source field.  Next ETL task will be to use OpenNLP to tag entities from the raw text and store those into ES.
