### ISSUE TITLE
Optimize and validate Google Font Usage

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#24]
<link href='https://fonts.googleapis.com/css?family=Jaldi:700' rel='stylesheet' type='text/css'>
     <link href='https://fonts.googleapis.com/css?family=Alegreya' rel='stylesheet' type='text/css'>
     <link href='https://fonts.googleapis.com/css?family=Original+Surfer' rel='stylesheet' type='text/css'>
     <link href='https://fonts.googleapis.com/css?family=Gurajada' rel='stylesheet' type='text/css'>
     <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

Each call requires going out to Google servers which can increase initial page load time. 

You can import multiple fonts in a single call as follows to improve performance:

    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Raleway|Gurajada">

More info can be found here: https://developers.google.com/fonts/docs/getting_started#specifying_font_families_and_styles_in_a_stylesheet_url

**Comment by dhuang89** [comment]
all fonts are imported in a single call
