### ISSUE TITLE
Refresh applicants view after marking a favorite

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#28]
Currently, when you mark an item as a favorite or archive, you need to refresh the page. We should sync the applicants list with the change.

favorite.$save() returns a promise. This can be used to trigger another query to refresh the page as follows:

favorite.$save().then(function(){
  $scope.applicants = Applicant.query();
});

**Comment by dhuang89** [comment]
page now refreshes when favorite button is pressed
