### ISSUE TITLE
getting search bar working

### ISSUE THREAD

**Issue by acobb6** [dataworks/internship-2016#35]

**Comment by dhuang89** [comment]
implemented angular filtering for now, which imitates a basic search function

**Comment by dhuang89** [comment]
filtering has been removed, search bar is now connected to elasticsearch. by entering a field of text and pressing the button, a new query is created.

**Comment by dhuang89** [comment]
search function does not work in firefox

**Comment by dhuang89** [comment]
search now works in firefox
