### ISSUE TITLE
Implement login/logout system

### ISSUE THREAD

**Issue by dhuang89** [dataworks/internship-2016#46]
Use Oauth 2.0 to create an authentication system

http://passportjs.org/

Application should be configurable to select different Oauth providers (Google, Github, Slack etc)

Having an authentication system will lead to new functionality being possible. For example, we can have an admin screen that would allow you to configure the machine learning parameters (Change Reston, list of tech we are looking for, etc).

**Comment by dhuang89** [comment]
idea has been scrapped

**Comment by davidmezzetti** [comment]
Re-opening to keep in queue, time permitting. 

node.js has a comprehensive library for this called passport.js

http://passportjs.org/

**Comment by davidmezzetti** [comment]
Before implementing this issue, we should add SSL support to the application. Otherwise, our tokens will be passed in plain text.

**Comment by dhuang89** [comment]
login and logout now work, just need to implement it to applicantView
