### ISSUE TITLE
Ensure that editor spacing/formatting is consistent

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#57]
Make sure the team is using a common standard for each editor chosen. For example, you can use tabs for spacing or have a tab be 4 spaces.

Without doing this, the code will drift to being inconsistently formatted once again. Looking at the code through the github webpage is a good way to double check it's consistently formatted.

**Comment by dhuang89** [comment]
it has been agreed upon to use tabs to indent, and keep the tab-width to 2
