### ISSUE TITLE
Modify Attachment stores to use Amazon S3

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#6]
Currently, attachments and uploads are stored as base64 strings in Elasticsearch. The ETL processes and application should instead use S3 binary files to implement this functionality.

We should allow this still to be stored in Elasticsearch via configuration parameters in the ETL processes and application.

The following link contains code to work with Amazon S3:
http://www.sparktutorials.net/reading-and-writing-s3-data-with-apache-spark
https://aws.amazon.com/sdk-for-node-js/

**Comment by gilberbe** [comment]
Getting this error: Exception in thread "main" java.lang.NoSuchMethodError: org.jets3t.service.impl.rest.httpclient.RestS3Service.<init>(Lorg/jets3t/service/security/AWSCredentials;)V

When trying to execute this code:
    sc.hadoopConfiguration.set("fs.s3n.awsAccessKeyId", keys.get(0))
    sc.hadoopConfiguration.set("fs.s3n.awsSecretAccessKey", keys.get(1))
    val fileData = sc.textFile("s3n://resumes.interns.dataworks-inc.com")

**Comment by davidmezzetti** [comment]
Ran out of time for this one. The application supports reading data from S3 but the attachment store continues to be within Elasticsearch.
