### ISSUE TITLE
Separate the machine learning from the ResumeParser process

### ISSUE THREAD

**Issue by goubew** [dataworks/internship-2016#60]
Right now, scores are being calculated as part of the resume parsing. Separating this into a new process will allow the scores on elasticsearch to be updated after model/feature changes without having to reparse each resume.

Changes include:
  1) Change ScoreCalculator into a runnable class (main function, spark config, cli options, etc.).
  2) Remove the ml code currently in ResumeParser, namely the w2v stuff, and put it in ScoreCalculator.

**Comment by gilberbe** [comment]
ML (w2v) code removed from ResumeParser
