### ISSUE TITLE
Finish feature extraction code

### ISSUE THREAD

**Issue by goubew** [dataworks/internship-2016#62]
Currently planned features include:
1) Number of Java/Hapoop/Spark keyword synonyms
2) Distance from the work location
3) Density of contact info
4) Resume length
5) GPA
6) Type of degree
7) Past titles

Since these feature scores are needed when both creating the model and testing against it, it is worth sharing this code between the two processes.

**Comment by gilberbe** [comment]
Done, scaling to 1-0
