### ISSUE TITLE
Create advanced search

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#64]
Currently, the system has a minimalist simple search that supports fielded searching. In order to complete issue #50, we should add an advanced search capability with the search fields broken out.

On the main page, we can have a toggle button that drops down a fielded search. The server would construct an elasticsearch query based on the populated fields. 

This and #50 are overall low priority issues.

**Comment by dhuang89** [comment]
dropdown menu has been added, and can now search by some majors and locations. only problem is that query appears back in the search bar, which makes making a new search more inconvenient that it should be. i've tried resetting $scope.searchText = searchText after the search which fixes it, but that method messes up infinite scroll, as nextPage relies on $scope.searchText for its query to function correctly

**Comment by dhuang89** [comment]
added another variable to mask the query in the search bar
