### ISSUE TITLE
Fix sorting by name

### ISSUE THREAD

**Issue by dhuang89** [dataworks/internship-2016#66]
Elasticsearch seems to favor uppercase letters over lowercase letters when sorting, which results in a list that is not truly alphabetically sorted. This can be fixed by implementing a lowercase filter:

https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-collations.html

http://stackoverflow.com/questions/22099906/unexpected-case-insensitive-string-sorting-in-elasticsearch

**Comment by davidmezzetti** [comment]
The following link at the top of the page gives a good explanation of what is happening.

https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-fields.html

This can be fixed by creating a custom mapping for the string fields we want to sort on.

**Comment by dhuang89** [comment]
created script for elasticsearch mappings in etl folder called 'create-elasticsearch-mappings.sh'

as of right now, the -XPUT call is failing as the current mapping has a different analyzer. to fix this, the index will likely need to be recreated

**Comment by dhuang89** [comment]
sorting by name now works. people with "name not found" appear on top, that's because their name string is an empty string.
