### ISSUE TITLE
Allow resume to be uploaded from web app

### ISSUE THREAD

**Issue by joeschweitzer** [dataworks/internship-2016#7]
Allow a resume to be uploaded from the web app which will then feed it to the Spark job (perhaps by storing to S3).

**Comment by nsudini** [comment]
The base64 strings should be in ES now

**Comment by gilberbe** [comment]
Script is working, can make some future improvements:
- Merge with ResumeParser/read-resume
- Pull from S3 instead of Elasticsearch
- Run automatically (i.e. every ~3 minutes)
