### ISSUE TITLE
Update NLP Logic to include calls to clearAdaptiveData

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#75]
EntityExtractor.extractEntities will never call clearAdaptiveData since it checks for the line being empty before processing. 

clearAdaptiveData only needs to be called once per document. This method should be changed to remove the logic to clear adaptive data. Instead a separate method should be created and called at the beginning of the extractEntities call.

More information on adaptive data can be found here: https://opennlp.apache.org/documentation/1.6.0/manual/opennlp.html

Search for clearAdaptiveData

**Comment by gilberbe** [comment]
Done, will push
