### ISSUE TITLE
Add loading image when pulling nextpage of results

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#76]
When the page is pulling in new results, we should use the loading mask function of the infinite scroll to give the user a visual indicator more results are loading.

You can create a separate div that is only shown on loading more results. You would use a flag that set ng-show when results are being pulled back from the server.

You can generate a loading image here:
http://loading.io/

**Comment by acobb6** [comment]
A loading icon has been added when data is being loaded.
