### ISSUE TITLE
Reporting and Analytics

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#78]
Elasticsearch has a rich framework for aggregating results. This can be used to create a summarization across large amounts of data. We have already used this for autocomplete functionality.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html

We should look into chart.js and HTML5 charting to build graphs over the search results. We can show graphs for things such as top skills, locations and other elements used for the ML job. This will give visual feedback and further help development of the ML processes. 

There are a number of different ways to lay this out. We can have an expandable section at the top/left/right. It would be best to have it integrated into the main page.

**Comment by mcmesser** [comment]
Kibana? https://www.elastic.co/downloads/kibana

**Comment by davidmezzetti** [comment]
Thank you for the comment, good point. We'll be sure to look at ways to integrate Kibana to handle reporting/analytics.
