### ISSUE TITLE
Modify labels query to improve scalability

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#79]
Currently, the labels query is using a query_string_query to filter ids for each drop down.

Consider the following type of query instead:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-ids-query.html

This is a low priority issue and should only be worked once other pieces of functionality such as ML and Analytics are complete.

**Comment by dhuang89** [comment]
queries have now been changed to add scalability. search functions and aggregations have been changed accordingly
