### ISSUE TITLE
ResumeReader Improvements

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#8]
1. Modify the tikaFunc method to use the PortableDataStream (a._2) vs the file path. This will enable support of non-local file systems (HDFS, S3). The PortableDataStream should be able to be directly passed to the parse method as opposed to creating file streams.

1. Add object and method level comments

1. Use the scopt command line parser as opposed to args. This will allow a more robust interface. See WordMap.scala for an example.

**Comment by gilberbe** [comment]
Part 1 complete, Spark now passes only the [PortableDataStream](https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/input/PortableDataStream.html) (the value of the [key-value RDD](https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/api/java/JavaPairRDD.html)) to the TikaFunc.  Spark still stores the files in the RDD as a key-value pair in the main method

**Comment by gilberbe** [comment]
2. Added comments

**Comment by gilberbe** [comment]
2. Added comments

**Comment by gilberbe** [comment]
Part 2: Added comments to method/object

**Comment by gilberbe** [comment]
Part 3: Will added command line arguments using scopt

**Comment by gilberbe** [comment]
Note: Method "tikaFunc" was renamed to "extractText"
