### ISSUE TITLE
Enhance ResumeGenerator to generate PDFs

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#82]
Currently, the ResumeGenerator creates a resume on the fly and prints to stdout. This should be enhanced to write PDFs out to file. PDFBox has a method called TextToPdf. These files can then be processed and scored.

We can use this to bulk generate more resumes.

**Comment by dhuang89** [comment]
ResumeGenerator has been edited to now generate a PDF file of the resume, but PDFBox does not like line feeds. Need to find a way to fix this for formatting

**Comment by dhuang89** [comment]
strings now stay within the pdf, but the substring method cuts up the strings in incorrect places. will need to fix this and then move the function calls to a different class

**Comment by dhuang89** [comment]
function is now complete. run the script, and the generated resume will be located in etl/data/generatedresumes
