### ISSUE TITLE
Add text classification feature to ML Job

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#83]
**Overview**
In the most successful ML projects, you will often build an ensemble of models. The results can be combined differently or even used as a feature in another model. This task here is to look into building a new feature for our existing model to label documents based on the text content.

**Hypothesis**
Favorite resumes are more likely to have similar terms and archived resumes are more likely to have similar terms.

**Implementation Strategies**
There are a number of ways to do this in increasing order of complexity. Start with the first one and go on to others only if necessary.

1.) Simple Bayes classifier. Similar to a spam filter. Looking for common words that are in your two labels and giving the likelihood of it being a class. Example of doing this can be found here: https://github.com/dataworks/internship-2015/tree/master/etl/Cleanser

2.) Paragraph vectors - Using dl4j/deep learning to classify. Example can be found here: https://github.com/kogecoo/dl4j-0.4-examples-scala/blob/master/src/main/scala/org/deeplearning4j/examples/nlp/paragraphvectors/ParagraphVectorsClassifierExample.scala

3.) Word2VecRNN - Combine word vectors and a recurrent neural network. Would be a project within itself. Example can be found here: https://github.com/kogecoo/dl4j-0.4-examples-scala/tree/master/src/main/scala/org/deeplearning4j/examples/recurrent/word2vecsentiment

**Comment by goubew** [comment]
A naive bayes model trained against term frequencies now works as a feature.
