### ISSUE TITLE
Check for null before adding rows in nextPage

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#88]
There is occasionally a race condition where nextPage is called before the initial query call is complete. The following line needs to check for null before calling concat. If it is null, the rows value can instead be set.

 $scope.applicants.rows = $scope.applicants.rows.concat(rows);

**Comment by dhuang89** [comment]
added: 
       if ($scope.applicants.rows == null) {
          $scope.applicants.rows = rows;
        } else {
          $scope.applicants.rows = $scope.applicants.rows.concat(rows);
        }

hopefully this fixes it. will re-open if problem comes back
