### ISSUE TITLE
Modify autocomplete to support multiple terms

### ISSUE THREAD

**Issue by dhuang89** [dataworks/internship-2016#91]
Currently, autocomplete is using aggregations to group the top terms in the index based on the query. But this only works for a single term.

The esservice.suggest method should be enhanced to support multiple terms. The logic would be modified as follows:

1.) Change the default operator for the query_string_query to AND
2.) Modify the include filter to only filter on the last term .*
  -For example for Java Dev, it would filter on Dev*
3.) For each result prepend all terms before the last term. For example if the completion results were [Developer, Develop], the results would be [Java Developer, Java Develop].

**Comment by davidmezzetti** [comment]
match_phrase_query is another alternative

**Comment by dhuang89** [comment]
autocomplete is now functional
