### ISSUE TITLE
Show different actions based on applicant type

### ISSUE THREAD

**Issue by dhuang89** [dataworks/internship-2016#92]
Currently, when you run a search, it will correctly return all records. But based on the type dropdown, it will only show those actions regardless of the current applicant label.

To fix this, we should modify the search query logic. When a search is executed, we need a new handler that will run another query getting the labels for each applicant found. The labels will then be added to the applicant object and returned.

On the front end side, if a query is executed, the dropdown should temporarily show "Search". The view logic will need to check if type exists and generate the action icons based on that if it's found. Otherwise, it will fallback to the default logic looking at the dropdown type.

**Comment by davidmezzetti** [comment]
When looking at this issue, look at #79
