### ISSUE TITLE
Build installation/configuration documentation

### ISSUE THREAD

**Issue by davidmezzetti** [dataworks/internship-2016#99]
Build documentation within the repository to allow someone to download, install and configure SmartHire with their own data and models.  Enhance the main README.md file and link to other files as necessary. 

For OpenNLP, you can link to the default models (http://opennlp.sourceforge.net/models-1.5/). You can also give instructions on how to train new models with our code/scripts against new data, given that the default models don't perform well against resumes.

You can edit MD files directly through the github interface which allows previewing formatting as you go. Otherwise, github atom has a markdown editor plugin.

You can test your documentation works by cloning the code locally to one of your laptops and trying to get the full stack working there without our data/models.

Good examples of documentation:
https://github.com/fchollet/keras
https://github.com/tensorflow/tensorflow
https://github.com/angular/material

**Comment by dhuang89** [comment]
Can use same Google doc in #102 

https://docs.google.com/document/d/1FLOjZ0vKrbbcGpgCg5d5_WTIwtT0zrNDVndNv78Cfzc/edit#

**Comment by goubew** [comment]
Documentation is there now for the main README and ETL README. Only the app README left.

**Comment by dhuang89** [comment]
app readme is now complete. will ask Joe about more details for Jenkins
